networks:
  ocnet:
    driver: bridge

services:
  api:
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ocnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      DSN: "mysql:password@tcp(mysql:3306)/currencies?parseTime=true"
      MIGRATIONS_PATH: "file://migrations"

  mysql:
    restart: always
    image: mysql:latest
    networks:
      - ocnet
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=currencies
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 2s
      retries: 10